import "./globals.css"
import type { Metadata } from "next"
import React, { ReactNode } from "react"
import { twMerge } from "tailwind-merge"
import { Concert_One, Questrial } from "next/font/google"
import dynamic from "next/dynamic"
import LinePattern from "@/components/patterns/LinePattern"
import Footer from "@/components/footer/Footer"

const Navigation = dynamic(() => import("@/components/navigation/Navigation"), { ssr: false })
const TopMarqueeBanner = dynamic(() => import("@/components/banners/TopMarqueeBanner"), { ssr: false })

const heading = Concert_One({ weight: ["400"], subsets: ["latin"], variable: "--font-heading" })
const sans = Questrial({ subsets: ["latin"], weight: ["400"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme={`system`} className={twMerge(`${heading.variable} ${sans.variable} scroll-smooth`)}>
      <body className={`font-sans bg-gray-100 dark:bg-gray-900 relative`}>
        <a
          className={`sr-only focus:not-sr-only focus:inline-block focus:px-3 focus:py-2 focus:font-bold rounded-md focus:absolute text-gray-100 bg-gray border-primary border-4 focus:top-1 active:bg-primary-500 active:text-gray focus:left-5 z-[500]`}
          href="#main"
        >
          Skip to main
        </a>
        <LinePattern
          className={`fixed opacity-75 -inset-1 mask-image-b mask-image-from-0 mask-image-to-50 mask-image-start-50 mask-image-end-60 stroke-2 dark:stroke-primary-500/50 drop-shadow-xl stroke-secondary/30`}
        />
        <Navigation />
        <div id="main">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
