import "./globals.css"
import type { Metadata } from "next"
import NewsletterBanner from "@/components/banners/NewsletterBanner"
import TopographyPattern from "@/components/patterns/TopographyPattern"
import React, { ReactNode } from "react"
import { twMerge } from "tailwind-merge"
import { Questrial, Rozha_One } from "next/font/google"
import Footer from "@/components/footer/Footer"
import dynamic from "next/dynamic"

const Navigation = dynamic(() => import("@/components/navigation/Navigation"), { ssr: false })
const TopMarqueeBanner = dynamic(() => import("@/components/banners/TopMarqueeBanner"), { ssr: false })

const rozha = Rozha_One({ weight: ["400"], subsets: ["latin"], variable: "--font-rozha" })
const questrial = Questrial({ subsets: ["latin"], weight: ["400"], variable: "--font-questrial" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme={`system`} className={twMerge(`${rozha.variable} ${questrial.variable}`)}>
      <body className={`font-sans`}>
        <a
          className={`sr-only shake focus:not-sr-only focus:inline-block focus:px-3 focus:py-2 focus:font-bold rounded-md focus:absolute text-secondary bg-primary border-secondary border-4  focus:top-1 focus:left-5 z-[500]`}
          href="#main"
        >
          Skip to main
        </a>
        <NewsletterBanner>Newsletter message</NewsletterBanner>
        <TopMarqueeBanner className={`shadow-block rounded-none -mx-3`} />
        <Navigation />
        <TopographyPattern className={`h-[400px] text-primary/20 fixed top-0 inset-x-0 -z-10 image-mask-b-0`} />
        <div id="main">{children}</div>
        <Footer />
      </body>
    </html>
  )
}
